name: campus_assistant
description: 校园万事通 Flutter 客户端
publish_to: none
version: 1.0.0+7
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  path_provider: 2.1.5
  image_picker: 1.2.0
  google_mlkit_text_recognition: 0.15.0
  flutter_local_notifications: 19.5.0
  timezone: 0.10.1
  url_launcher: 6.3.2
  flutter_secure_storage: 9.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/demo-library.json
    - assets/schools.json
