name: campus_assistant
description: 校园万事通 Flutter 客户端
publish_to: none
version: 0.3.0+3
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/demo-library.json
